name: PR Workflow

on:
  pull_request:
    branches:
      - main
      - dev/*
      - release/*

jobs:
  build:
    name: Build Docker Image for PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install --save-dev semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/github @semantic-release/git

      - name: Install Dependencies
        run: npm install

      - name: Extract Base Version from Branch Name
        id: extract_version
        run: |
          # Get the current branch name
          branch_name=$(echo "${GITHUB_REF##*/}")
        
          # Check if it's in the format dev/X.Y.Z (adjust this for release branches)
          if [[ $branch_name =~ dev/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            base_version="${BASH_REMATCH[1]}"
            echo "Branch version found: $base_version"
          else
            # Default to 1.0.0 if no specific base version is found
            echo "Branch version not found. Using default version: 1.0.0"
            base_version="1.0.0"
          fi
          echo "Base version: $base_version"
          echo "base_version=$base_version" >> $GITHUB_ENV          

      - name: Get Git Commit Hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Version from Semantic Release
        id: get_version
        run: |
          version=$(npx semantic-release --dry-run --tag "${{ env.base_version }}"| grep -oP 'next version is \K.*')
          echo "version=$version" >> $GITHUB_ENV

      - name: Build Docker Image with Version and Commit Hash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/demo-cicd-client:${{ env.version }}-${{ env.commit_hash }} .
